# Generated by Django 4.2.19 on 2025-03-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecord',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrecord',
            name='location',
        ),
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
        migrations.DeleteModel(
            name='HistoricalRecord',
        ),
    ]
